name: CI

on:
  push:
    branches: ["dev"]

jobs:
  test:
    runs-on: ${{vars.HOST_IMAGE}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{vars.PYTHON_VERSION}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --upgrade -r requirements.txt
